modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module

      app_name: SimApp

      # During begin block slashing happens after distr.BeginBlocker so that
      # there is nothing left over in the validator fee pool, so as to keep the
      # CanWithdrawInvariant invariant.
      # NOTE: staking module is required if HistoricalEntries param > 0
      # NOTE: capability module's beginblocker must come before any modules using capabilities (e.g. IBC)
      begin_blockers:
        [
          perm,
          auth,
          node,
          bank,
          slashing,
          crisis,
          evidence,
          identity,
          feegrant,
          upgrade,
          params,
          genutil,
          consensus,
          cparams,
        ]

      end_blockers:
        [
          perm,
          auth,
          node,
          bank,
          slashing,
          crisis,
          evidence,
          identity,
          feegrant,
          upgrade,
          params,
          genutil,
          consensus,
          cparams,
        ]

      init_genesis:
        [
          perm,
          auth,
          node,
          bank,
          slashing,
          crisis,
          evidence,
          identity,
          feegrant,
          upgrade,
          params,
          genutil,
          consensus,
          cparams,
        ]

      override_store_keys:
        - module_name: auth
          kv_store_key: acc

  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: cosmos
      module_account_permissions:
        - account: fee_collector
        - account: cparams

  - name: params
    config:
      "@type": cosmos.params.module.v1.Module

  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config

  - name: feegrant
    config:
      "@type": cosmos.feegrant.module.v1.Module

  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module

  - name: capability
    config:
      "@type": cosmos.capability.module.v1.Module
      seal_keeper: true

  - name: crisis
    config:
      "@type": cosmos.crisis.module.v1.Module

  - name: evidence
    config:
      "@type": cosmos.evidence.module.v1.Module

  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module

  - name: cparams
    config:
      "@type": iritamod.params.module.v1.Module
      msg_urls: [
        /cosmos.auth.v1beta1.MsgUpdateParams,
        /cosmos.bank.v1beta1.MsgUpdateParams,
        /cosmos.consensus.v1.MsgUpdateParams,
        /cosmos.crisis.v1beta1.MsgUpdateParams,
        /irita.slashing.MsgUpdateParams,
        /irita.node.MsgUpdateParams,
      ]

  - name: slashing
    config:
      "@type": iritamod.slashing.module.v1.Module

  - name: perm
    config:
      "@type": iritamod.perm.module.v1.Module

  - name: identity
    config:
      "@type": iritamod.identity.module.v1.Module

  - name: node
    config:
      "@type": iritamod.node.module.v1.Module

  - name: upgrade
    config:
      "@type": iritamod.upgrade.module.v1.Module