modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module

      app_name: SimApp

      # During begin block slashing happens after distr.BeginBlocker so that
      # there is nothing left over in the validator fee pool, so as to keep the
      # CanWithdrawInvariant invariant.
      # NOTE: staking module is required if HistoricalEntries param > 0
      # NOTE: capability module's beginblocker must come before any modules using capabilities (e.g. IBC)
      begin_blockers:
        [
          upgrade,
          capability,
          mint,
          distribution,
          slashing,
          evidence,
          staking,
          auth,
          bank,
          gov,
          crisis,
          genutil,
          authz,
          feegrant,
          nft,
          group,
          params,
          vesting,
          token,
          mt,
          htlc,
          record,
          coinswap,
          service,
          oracle,
          random,
          farm,
          consensus,
        ]

      end_blockers:
        [
          crisis,
          gov,
          staking,
          capability,
          auth,
          bank,
          distribution,
          slashing,
          mint,
          genutil,
          evidence,
          authz,
          feegrant,
          nft,
          group,
          params,
          upgrade,
          vesting,
          token,
          mt,
          htlc,
          record,
          coinswap,
          service,
          oracle,
          random,
          farm,
          consensus,
        ]

      init_genesis:
        [
          capability,
          auth,
          authz,
          bank,
          distribution,
          staking,
          slashing,
          gov,
          group,
          mint,
          crisis,
          genutil,
          evidence,
          feegrant,
          params,
          upgrade,
          vesting,
          token,
          nft,
          mt,
          htlc,
          record,
          coinswap,
          service,
          oracle,
          random,
          farm,
          consensus,
        ]   

      override_store_keys:
        - module_name: auth
          kv_store_key: acc

  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: cosmos
      module_account_permissions:
        - account: fee_collector
        - account: distribution
        - account: mint
          permissions: [minter]
        - account: bonded_tokens_pool
          permissions: [burner, staking]
        - account: not_bonded_tokens_pool
          permissions: [burner, staking]
        - account: gov
          permissions: [burner]
        - account: nft
        - account: token
          permissions: [minter,burner]
        - account: htlc
          permissions: [minter,burner]
        - account: coinswap
          permissions: [minter,burner]
        - account: service_deposit_account
          permissions: [burner]
        - account: service_request_account
        - account: service_fee_collector
          permissions: [burner]
        - account: farm
          permissions: [burner]
        - account: reward_collector
        - account: escrow_collector
        - account: mt


  - name: params
    config:
      "@type": cosmos.params.module.v1.Module

  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config

  - name: feegrant
    config:
      "@type": cosmos.feegrant.module.v1.Module

  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module

  - name: authz
    config:
      "@type": cosmos.authz.module.v1.Module

  - name: capability
    config:
      "@type": cosmos.capability.module.v1.Module
      seal_keeper: true

  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module

  - name: group
    config:
      "@type": cosmos.group.module.v1.Module
      max_metadata_len: 255
      max_execution_period: "1209600s"

  - name: crisis
    config:
      "@type": cosmos.crisis.module.v1.Module

  - name: slashing
    config:
      "@type": cosmos.slashing.module.v1.Module

  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module

  - name: mint
    config:
      "@type": cosmos.mint.module.v1.Module

  - name: evidence
    config:
      "@type": cosmos.evidence.module.v1.Module

  - name: distribution
    config:
      "@type": cosmos.distribution.module.v1.Module

  - name: vesting
    config:
      "@type": cosmos.vesting.module.v1.Module

  - name: upgrade
    config:
      "@type": cosmos.upgrade.module.v1.Module

  - name: gov
    config:
      "@type": cosmos.gov.module.v1.Module
      max_metadata_len: 255 

  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module

  - name: nft
    config:
      "@type": irismod.nft.module.v1.Module

  - name: coinswap
    config:
      "@type": irismod.coinswap.module.v1.Module
      fee_collector_name: "fee_collector"
  
  - name: farm
    config:
      "@type": irismod.farm.module.v1.Module
      fee_collector_name: "fee_collector"
      community_pool_name: "distribution"

  - name: htlc
    config:
      "@type": irismod.htlc.module.v1.Module

  - name: mt
    config:
      "@type": irismod.mt.module.v1.Module
  
  - name: oracle
    config:
      "@type": irismod.oracle.module.v1.Module
  
  - name: random
    config:
      "@type": irismod.random.module.v1.Module

  - name: record
    config:
      "@type": irismod.record.module.v1.Module

  - name: identity
    config:
      "@type": iritamod.identity.module.v1.Module

  - name: node
    config:
      "@type": iritamod.node.module.v1.Module

  - name: service
    config:
      "@type": irismod.service.module.v1.Module
      fee_collector_name: "service_fee_collector"

  - name: token
    config:
      "@type": irismod.token.module.v1.Module
      fee_collector_name: "fee_collector"